#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ENV_NAME="${ENV_NAME:-testnet}"
DEPLOYMENT_FILE="${DEPLOYMENT_FILE:-$ROOT_DIR/deployments/testnet.json}"
MATCHER_ENV_FILE="${MATCHER_ENV_FILE:-$ROOT_DIR/services/matcher/.env.testnet}"

NETWORK_NAME="${NETWORK_NAME:-Sinergy Testnet}"
ROLLUP_CHAIN_ID="${ROLLUP_CHAIN_ID:-sinergy-testnet}"
L1_CHAIN_ID="${L1_CHAIN_ID:-initiation-2}"
OPINIT_BRIDGE_ID="${OPINIT_BRIDGE_ID:-1735}"
TENDERMINT_RPC_URL="${TENDERMINT_RPC_URL:-https://TODO_TENDERMINT_RPC_URL}"
JSON_RPC_URL="${JSON_RPC_URL:-https://TODO_JSON_RPC_URL}"
WS_URL="${WS_URL:-wss://TODO_EVM_WS_URL}"
REST_URL="${REST_URL:-https://TODO_REST_URL}"
EVM_CHAIN_ID="${EVM_CHAIN_ID:-0}"
EVM_CHAIN_ID_HEX="${EVM_CHAIN_ID_HEX:-0x0}"
GAS_DENOM="${GAS_DENOM:-GAS}"
NATIVE_CURRENCY_NAME="${NATIVE_CURRENCY_NAME:-Gas}"
NATIVE_CURRENCY_SYMBOL="${NATIVE_CURRENCY_SYMBOL:-$GAS_DENOM}"
NATIVE_CURRENCY_DECIMALS="${NATIVE_CURRENCY_DECIMALS:-18}"
EXPLORER_URL="${EXPLORER_URL:-https://TODO_EXPLORER_URL}"

exec "$ROOT_DIR/scripts/deploy-local.sh"
